// Editorial expansions based on the supplied 2021 textbook, not verbatim quotations.
import fs from 'node:fs';
const file = new URL('../data/chapters.json', import.meta.url);
const chapters = JSON.parse(fs.readFileSync(file, 'utf8'));
const content = {
 '1-1': [
  ['Bối cảnh kinh tế và phong trào công nhân','Đại công nghiệp tạo ra năng lực sản xuất lớn, đồng thời tập trung đông đảo người lao động trong các nhà máy. Sự phát triển ấy làm rõ mâu thuẫn giữa tính xã hội hóa của sản xuất và chế độ chiếm hữu tư nhân tư bản chủ nghĩa. Đây là điều kiện kinh tế để đặt vấn đề về một hình thức tổ chức xã hội mới.','Phong trào công nhân ở Anh, Pháp và Đức cho thấy giai cấp công nhân đã bước vào đấu tranh với tư cách một lực lượng chính trị. Những hạn chế của các phong trào ban đầu đặt ra nhu cầu chuyển từ đấu tranh tự phát sang đấu tranh có tổ chức và có lý luận khoa học dẫn đường.'],
  ['Ba tiền đề khoa học tự nhiên','Học thuyết tế bào giúp nhận thức sự thống nhất của giới sinh vật; định luật bảo toàn và chuyển hóa năng lượng cho thấy mối liên hệ, sự chuyển hóa của các hình thức vận động; học thuyết tiến hóa củng cố cách nhìn về sự phát triển của thế giới sống. Các thành tựu này góp phần bác bỏ cách giải thích xem sự vật hoàn toàn bất biến và tách rời.','Không nên hiểu rằng một phát minh tự nhiên trực tiếp chứng minh một chế độ xã hội. Vai trò của chúng là cung cấp cơ sở khoa học cho thế giới quan và cách nghiên cứu mà các nhà sáng lập vận dụng khi phân tích xã hội.'],
  ['Kế thừa và vượt qua tư tưởng không tưởng','Triết học cổ điển Đức, kinh tế chính trị học cổ điển Anh và chủ nghĩa xã hội không tưởng – phê phán cung cấp những thành tựu tư tưởng quan trọng. Mác và Ăngghen tiếp thu có phê phán, cải tạo phương pháp nghiên cứu và giải thích các quan hệ xã hội từ đời sống vật chất.','Các nhà xã hội chủ nghĩa không tưởng đã phê phán bất công và đề xuất nhiều hình dung tiến bộ. Giới hạn của họ là chưa chỉ ra đầy đủ quy luật vận động, lực lượng xã hội và con đường thực hiện việc cải biến xã hội. Phân biệt điều kiện, tiền đề và vai trò chủ thể giúp tránh giải thích sự ra đời của môn học bằng một nguyên nhân duy nhất.']
 ],
 '1-2': [
  ['Vai trò của các nhà sáng lập','Mác và Ăngghen kết hợp nghiên cứu triết học, kinh tế chính trị với việc tham gia và tổng kết phong trào công nhân. Sự chuyển biến từ chủ nghĩa duy tâm sang chủ nghĩa duy vật, từ lập trường dân chủ cách mạng sang lập trường cộng sản tạo ra bước chuyển trong cách đặt và giải quyết vấn đề xã hội.','Vai trò chủ quan thể hiện ở năng lực phát hiện quy luật, khái quát thực tiễn và xây dựng một hệ thống lý luận. Điều kiện khách quan tạo khả năng, nhưng hoạt động của các nhà sáng lập mới biến khả năng đó thành học thuyết cụ thể.'],
  ['Ý nghĩa của ba phát kiến','Chủ nghĩa duy vật lịch sử giải thích xã hội thông qua sản xuất vật chất, quan hệ sản xuất và sự vận động của các hình thái kinh tế – xã hội. Học thuyết giá trị thặng dư làm rõ cơ chế tạo ra và chiếm hữu giá trị thặng dư trong nền sản xuất tư bản chủ nghĩa.','Trên cơ sở đó, việc luận chứng sứ mệnh lịch sử của giai cấp công nhân xác định lực lượng có khả năng tổ chức quá trình cải biến xã hội. Ba phát kiến liên hệ với nhau: cơ sở phương pháp luận, phân tích cơ chế kinh tế và xác định chủ thể lịch sử. Không nên học chúng như ba khái niệm rời rạc.'],
  ['Vì sao mốc 1848 quan trọng?','Tuyên ngôn của Đảng Cộng sản trình bày một cách có hệ thống quan điểm về đấu tranh giai cấp, vai trò của giai cấp công nhân và tổ chức chính trị của giai cấp ấy. Giáo trình lấy sự ra đời của tác phẩm năm 1848 làm dấu mốc ra đời của Chủ nghĩa xã hội khoa học.','Ý nghĩa của dấu mốc nằm ở sự hình thành hệ thống lý luận và chương trình hành động, chứ không phải mọi luận điểm đã hoàn tất một lần cho mãi mãi. Những kinh nghiệm thực tiễn tiếp theo tiếp tục được tổng kết để bổ sung và phát triển lý luận.']
 ],
 '1-3': [
  ['Mác và Ăngghen phát triển lý luận sau 1848','Thực tiễn đấu tranh của công nhân, sự phát triển của chủ nghĩa tư bản và kinh nghiệm Công xã Pari năm 1871 cung cấp chất liệu để các nhà sáng lập bổ sung nhận thức về cách mạng, nhà nước và tổ chức của giai cấp công nhân. Quá trình phát triển lý luận luôn gắn với những vấn đề do lịch sử đặt ra.','Khi đọc một luận điểm, cần xác định thời điểm ra đời, vấn đề thực tiễn mà nó giải quyết và các điều kiện áp dụng. Đây là cách tránh biến kết luận từ một hoàn cảnh cụ thể thành công thức dùng cho mọi xã hội.'],
  ['Lênin vận dụng trong điều kiện lịch sử mới','V.I. Lênin phát triển lý luận trong bối cảnh chủ nghĩa tư bản chuyển sang giai đoạn đế quốc chủ nghĩa và phong trào cách mạng có những đặc điểm mới. Các vấn đề về đảng kiểu mới, cách mạng, nhà nước, thời kỳ quá độ, dân tộc và liên minh được nghiên cứu trong quan hệ với thực tiễn.','Sau Cách mạng Tháng Mười, nhiệm vụ xây dựng xã hội mới đòi hỏi giải quyết các vấn đề tổ chức kinh tế và quản lý xã hội. Những điều chỉnh chính sách cho thấy cần phân biệt mục tiêu dài hạn với bước đi, biện pháp và điều kiện thực hiện.'],
  ['Vận dụng và phát triển ở Việt Nam','Trong phạm vi giáo trình 2021, quá trình cách mạng và đổi mới ở Việt Nam được xem là sự vận dụng các nguyên lý vào điều kiện lịch sử cụ thể của đất nước. Việc tổng kết thành tựu, khó khăn và hạn chế là một phần của quá trình phát triển nhận thức.','Một cách học phù hợp là đối chiếu ba lớp: nguyên lý lý luận, lựa chọn thực tiễn và kết quả thực hiện. Tránh suy luận rằng kết quả của một mô hình lịch sử riêng biệt tự động đại diện cho toàn bộ học thuyết, hoặc rằng lý luận có thể thay cho phân tích thực tiễn.']
 ],
 '1-4': [
  ['Phạm vi nghiên cứu của môn học','Theo nghĩa rộng, chủ nghĩa xã hội khoa học được dùng để nói đến chủ nghĩa Mác – Lênin với tư cách sự luận chứng về quá trình chuyển từ chủ nghĩa tư bản lên chủ nghĩa xã hội và chủ nghĩa cộng sản. Theo nghĩa hẹp, đây là một trong ba bộ phận hợp thành, cùng với triết học và kinh tế chính trị học Mác – Lênin.','Môn học này tập trung vào nghĩa hẹp: các quy luật và tính quy luật chính trị – xã hội, những điều kiện và con đường thực hiện sứ mệnh lịch sử của giai cấp công nhân. Nó sử dụng thành quả của hai bộ phận còn lại nhưng có đối tượng nghiên cứu riêng.'],
  ['Cách kết hợp các phương pháp','Phương pháp lịch sử xem xét sự kiện theo quá trình hình thành và điều kiện cụ thể; phương pháp lôgíc khái quát những quan hệ bản chất từ quá trình ấy. Kết hợp hai phương pháp giúp vừa tránh kể sự kiện đơn thuần, vừa tránh lập luận trừu tượng không có căn cứ lịch sử.','Phân tích chính trị – xã hội xem xét chủ thể, lợi ích, quyền lực, tổ chức và điều kiện thực hiện. So sánh, khảo sát và các phương pháp liên ngành bổ sung dữ liệu, nhưng phải kiểm tra độ tin cậy và sự tương đồng của những trường hợp được so sánh.'],
  ['Từ học khái niệm đến phân tích một vấn đề','Có thể bắt đầu bằng việc xác định câu hỏi, mô tả bối cảnh, thu thập dữ kiện, lựa chọn khái niệm liên quan rồi giải thích mối liên hệ giữa các yếu tố. Kết luận cần nêu rõ căn cứ và giới hạn thay vì chỉ khẳng định điều mình mong muốn.','Ý nghĩa học tập gồm nâng cao nhận thức lý luận, rèn phương pháp phân tích và hình thành thái độ chủ động trước các vấn đề xã hội. Học có căn cứ còn đòi hỏi phân biệt nội dung giáo trình, phần diễn giải và ví dụ giả định.']
 ],
 '2-1': [
  ['Hai phương diện nhận diện giai cấp công nhân','Về kinh tế – xã hội, công nhân là những người lao động trực tiếp hoặc gián tiếp vận hành công cụ sản xuất có tính chất công nghiệp ngày càng hiện đại và xã hội hóa. Lao động của họ gắn với tổ chức, kỷ luật, hợp tác và sự phụ thuộc giữa nhiều khâu trong quá trình sản xuất.','Về chính trị – xã hội, khi phân tích trong chủ nghĩa tư bản, cần xem quan hệ của người lao động với tư liệu sản xuất chủ yếu và việc bán sức lao động. Hai phương diện phải được đặt trong cùng một bối cảnh; hình thức thao tác, trang phục hay tên nghề riêng lẻ chưa đủ để xác định.'],
  ['Những đặc điểm gắn với đại công nghiệp','Lao động công nghiệp hình thành tác phong hợp tác, kỷ luật và khả năng tổ chức. Do sản xuất có tính xã hội hóa cao, thay đổi ở một bộ phận có thể ảnh hưởng tới toàn bộ hệ thống, làm rõ quan hệ giữa lợi ích cá nhân và lợi ích tập thể.','Giai cấp công nhân không phải một nhóm đồng nhất về trình độ, ngành nghề hoặc thu nhập. Sự đa dạng ấy không xóa bỏ nhu cầu nghiên cứu các đặc điểm chung, nhưng nhắc người học phải phân biệt đặc điểm của giai cấp với hoàn cảnh của từng cá nhân.'],
  ['Công nhân và các nhóm lao động khác','Người làm việc bằng trí óc vẫn có thể tham gia lao động công nghiệp hiện đại; sử dụng máy tính không tự động làm mất đặc điểm công nhân. Ngược lại, mọi người có việc làm hưởng lương cũng không thể được xếp vào một nhóm chỉ từ dấu hiệu tiền lương.','Muốn phân tích một trường hợp, cần hỏi người đó tham gia quá trình sản xuất nào, quan hệ với tư liệu sản xuất ra sao, quyền quản lý và hưởng lợi được tổ chức thế nào. Đây là bộ câu hỏi nghiên cứu, không phải quy tắc gán nhãn cá nhân một cách máy móc.']
 ],
 '2-2': [
  ['Nội dung kinh tế','Giai cấp công nhân gắn với phát triển lực lượng sản xuất và xây dựng cơ sở vật chất – kỹ thuật cho xã hội mới. Nội dung kinh tế không chỉ là làm ra nhiều sản phẩm mà còn liên quan đến tổ chức lao động, nâng cao năng suất và xây dựng quan hệ sản xuất phù hợp.','Quá trình ấy cần sự phối hợp với các lực lượng lao động khác. Khi vận dụng, cần phân tích cả năng lực công nghệ, trình độ người lao động, cơ chế quản lý và phân phối; không đồng nhất tăng trưởng sản lượng với việc hoàn thành toàn bộ sứ mệnh.'],
  ['Nội dung chính trị – xã hội','Thông qua đảng của mình và liên minh với nhân dân lao động, giai cấp công nhân thực hiện nhiệm vụ cải biến quyền lực chính trị và xây dựng nhà nước, tổ chức quản lý xã hội mới. Nội dung này gắn với việc thực hiện quyền làm chủ của nhân dân.','Sự chuyển biến chính trị cần điều kiện tổ chức và sự tham gia của các lực lượng xã hội. Không nên hiểu sứ mệnh lịch sử như kết quả tự động của vị trí kinh tế, hoặc nhiệm vụ mà một số cá nhân có thể thực hiện thay cho cả quá trình xã hội.'],
  ['Nội dung văn hóa – tư tưởng','Nội dung văn hóa – tư tưởng bao gồm xây dựng hệ giá trị mới, nâng cao trình độ nhận thức và phát triển con người. Việc khắc phục những quan niệm và tập quán không phù hợp phải gắn với giáo dục, đời sống văn hóa và điều kiện kinh tế – xã hội.','Ba nội dung hỗ trợ nhau: kinh tế tạo cơ sở vật chất, chính trị – xã hội tạo điều kiện tổ chức, văn hóa – tư tưởng định hướng giá trị và hành động. Khi phân tích một ví dụ thực tiễn, cần chỉ ra nó minh họa nội dung nào và những nội dung nào chưa được thể hiện.']
 ],
 '2-3': [
  ['Địa vị kinh tế tạo khả năng lịch sử','Giai cấp công nhân là sản phẩm và chủ thể của đại công nghiệp, gắn với lực lượng sản xuất tiên tiến và quá trình sản xuất xã hội hóa. Vị trí đó tạo điều kiện để tham gia tổ chức một phương thức sản xuất mới và khắc phục những quan hệ không còn phù hợp với sự phát triển của lực lượng sản xuất.','Trong chủ nghĩa tư bản, việc không nắm tư liệu sản xuất chủ yếu và phải bán sức lao động làm rõ mối quan hệ lợi ích của công nhân với sự cải biến quan hệ sản xuất. Đây là cơ sở phân tích ở cấp độ giai cấp, cần tránh suy luận trực tiếp từ mức sống của một người.'],
  ['Địa vị chính trị – xã hội và đặc điểm tổ chức','Lao động trong đại công nghiệp rèn khả năng tổ chức, kỷ luật và hợp tác. Những đặc điểm đó là điều kiện thuận lợi cho hành động tập thể, nhưng không có nghĩa mọi cá nhân tự nhiên có ý thức và năng lực chính trị giống nhau.','Từ khả năng khách quan đến kết quả thực tế còn phụ thuộc sự trưởng thành của phong trào, trình độ nhận thức, tổ chức lãnh đạo và quan hệ với các lực lượng xã hội khác. Vì vậy phải phân biệt điều kiện khách quan với việc hiện thực hóa điều kiện ấy.'],
  ['Những nhân tố chủ quan quyết định việc thực hiện','Sự phát triển của giai cấp công nhân về số lượng và chất lượng gồm trình độ chuyên môn, ý thức tổ chức, năng lực nhận thức và hoạt động thực tiễn. Đảng Cộng sản là nhân tố chủ quan quan trọng trong việc tổ chức, lãnh đạo và kết nối lý luận với phong trào.','Liên minh với giai cấp nông dân và các lực lượng lao động khác tạo cơ sở xã hội để thực hiện nhiệm vụ. Một phân tích đầy đủ cần xem đồng thời sự phát triển của công nhân, vai trò của tổ chức chính trị và sức mạnh của liên minh.']
 ],
 '2-4': [
  ['Những điểm ổn định và biến đổi của công nhân hiện đại','Công nhân hiện đại vẫn gắn với phương thức sản xuất công nghiệp và tính xã hội hóa của lao động. Đồng thời, thay đổi công nghệ làm tăng lao động vận hành, thiết kế, bảo trì, quản lý hệ thống và các công việc đòi hỏi tri thức chuyên môn cao.','Xu hướng trí tuệ hóa và những thay đổi về mức sống, cơ cấu nghề nghiệp không thể tự nó giải quyết câu hỏi về quan hệ sở hữu và quản lý. Cần phân biệt thay đổi công cụ lao động với thay đổi vị trí trong quan hệ sản xuất.'],
  ['Đặc điểm giai cấp công nhân Việt Nam','Giáo trình phân tích sự hình thành của công nhân Việt Nam trong điều kiện lịch sử đặc thù, sự gắn bó với dân tộc và quan hệ gần gũi với nông dân cùng các tầng lớp lao động. Những đặc điểm ấy ảnh hưởng đến vai trò chính trị và cơ sở của liên minh.','Trong quá trình công nghiệp hóa và hội nhập, công nhân làm việc ở nhiều ngành và thành phần kinh tế. Việc phát triển đội ngũ cần chú ý cả trình độ nghề nghiệp, tác phong công nghiệp, đời sống vật chất – tinh thần và năng lực tham gia các hoạt động xã hội.'],
  ['Phương hướng phát triển và cách liên hệ','Các phương hướng trong giáo trình gồm nâng cao chất lượng đào tạo, phát triển số lượng và cơ cấu phù hợp, bảo đảm điều kiện sống và làm việc, củng cố tổ chức và ý thức chính trị. Xây dựng công nhân phải đặt trong quan hệ với chiến lược phát triển kinh tế và liên minh xã hội.','Sinh viên có thể liên hệ qua việc học nghề, rèn năng lực hợp tác, cập nhật công nghệ và tìm hiểu điều kiện lao động. Các ví dụ công nghệ trong website là giả định, nhằm luyện phân tích; không phải số liệu mô tả thực trạng hiện nay.']
 ],
 '3-1': [
  ['Vị trí của chủ nghĩa xã hội trong hình thái cộng sản chủ nghĩa','Giáo trình phân biệt giai đoạn thấp và giai đoạn cao của hình thái kinh tế – xã hội cộng sản chủ nghĩa. Chủ nghĩa xã hội là giai đoạn thấp, có những điều kiện và giới hạn lịch sử nhất định; thời kỳ quá độ là quá trình cải biến từ xã hội cũ sang xã hội mới.','Cần tránh đồng nhất mục tiêu của giai đoạn cao với những điều kiện có thể đạt ngay trong giai đoạn thấp. Cách phân kỳ giúp lý giải vì sao việc xây dựng xã hội mới cần thời gian, cơ sở vật chất và những bước phát triển phù hợp.'],
  ['Điều kiện ra đời','Sự phát triển của lực lượng sản xuất và mâu thuẫn với quan hệ sản xuất tư bản chủ nghĩa tạo cơ sở kinh tế cho sự thay thế hình thái xã hội. Sự trưởng thành của giai cấp công nhân và tổ chức chính trị của giai cấp ấy là điều kiện xã hội – chính trị quan trọng.','Điều kiện kinh tế và điều kiện chính trị – xã hội liên hệ chặt chẽ. Không nên hiểu sự chuyển biến là kết quả tự phát chỉ do tăng trưởng kinh tế, cũng không thể chỉ dựa vào mong muốn chủ quan mà thiếu nền tảng vật chất.'],
  ['Sáu đặc trưng bản chất trong giáo trình','Các đặc trưng được trình bày gồm: giải phóng giai cấp, dân tộc, xã hội và con người, tạo điều kiện phát triển toàn diện; nhân dân lao động làm chủ; nền kinh tế phát triển cao dựa trên lực lượng sản xuất hiện đại và công hữu tư liệu sản xuất chủ yếu.','Ba đặc trưng còn lại là nhà nước kiểu mới mang bản chất giai cấp công nhân, đại biểu cho lợi ích và ý chí nhân dân lao động; nền văn hóa phát triển cao kế thừa giá trị dân tộc và nhân loại; bình đẳng, đoàn kết giữa các dân tộc và quan hệ hữu nghị, hợp tác với nhân dân các nước. Đây là một chỉnh thể, không thể đánh giá xã hội chỉ bằng một dấu hiệu.']
 ],
 '3-2': [
  ['Vì sao cần thời kỳ quá độ?','Chủ nghĩa tư bản và chủ nghĩa xã hội khác nhau về cơ sở kinh tế, tổ chức quyền lực và đời sống văn hóa – xã hội. Những yếu tố của xã hội mới cần được xây dựng và phát triển; giành được quyền lực chính trị không đồng nghĩa hoàn thành ngay việc cải biến mọi quan hệ xã hội.','Giáo trình phân biệt quá độ trực tiếp và quá độ gián tiếp trong những điều kiện lịch sử khác nhau. Độ dài và bước đi của quá trình phụ thuộc điểm xuất phát, nguồn lực và bối cảnh của từng quốc gia, vì vậy không có lịch trình cơ học áp dụng giống nhau.'],
  ['Sự đan xen trên các lĩnh vực','Về kinh tế, nhiều thành phần và hình thức sở hữu cùng tồn tại; về chính trị, việc xây dựng và bảo vệ chính quyền mới gắn với tổ chức quản lý xã hội. Những yếu tố cũ và mới tác động lẫn nhau trong một quá trình cải biến lâu dài.','Về tư tưởng – văn hóa, hệ giá trị mới hình thành trong điều kiện còn nhiều quan niệm và tập quán khác nhau. Về xã hội, vẫn tồn tại các giai cấp, tầng lớp, khác biệt và bất bình đẳng cần giải quyết từng bước. Sự đan xen không đồng nghĩa không có định hướng phát triển.'],
  ['Cách phân tích một hiện tượng trong thời kỳ quá độ','Khi gặp một hiện tượng như nhiều hình thức sở hữu hoặc chênh lệch trình độ phát triển, cần xác định nó thuộc lĩnh vực nào, nguyên nhân lịch sử và vai trò trong toàn bộ quá trình. Tránh lấy một doanh nghiệp hay một trường hợp để kết luận về bản chất của cả xã hội.','Phân biệt mục tiêu, điều kiện hiện có và nhiệm vụ chuyển đổi giúp nhận diện khoảng cách cần giải quyết. Phân tích còn phải xem việc phát triển lực lượng sản xuất có đi cùng cải thiện tổ chức, phân phối và cơ hội tham gia hay không.']
 ],
 '3-3': [
  ['Điểm xuất phát và tính tất yếu của lựa chọn','Giáo trình đặt con đường quá độ ở Việt Nam trong bối cảnh lịch sử của một nước có điểm xuất phát kinh tế thấp và trải qua đấu tranh giải phóng dân tộc. Việc lựa chọn con đường phát triển được phân tích trong quan hệ giữa điều kiện trong nước và xu thế thời đại.','Quá trình ấy đặt ra nhiệm vụ đồng thời xây dựng cơ sở vật chất, phát triển con người và hoàn thiện tổ chức xã hội. Điểm xuất phát thấp làm nổi bật nhu cầu phát huy nguồn lực trong nước và tiếp thu những thành tựu của nhân loại.'],
  ['Hiểu đúng việc bỏ qua chế độ tư bản chủ nghĩa','Bỏ qua được giải thích là bỏ qua việc xác lập vị trí thống trị của quan hệ sản xuất và kiến trúc thượng tầng tư bản chủ nghĩa. Điều đó không có nghĩa phủ nhận toàn bộ thành tựu khoa học, công nghệ, kinh nghiệm quản lý và văn hóa mà nhân loại đạt được trong quá trình phát triển.','Tiếp thu phải có chọn lọc và phù hợp điều kiện cụ thể. Không thể đồng nhất sử dụng cơ chế thị trường hoặc công nghệ tiên tiến với việc tự động xác lập một chế độ xã hội; cần phân tích vị trí, vai trò và định hướng của chúng trong cả hệ thống.'],
  ['Nhiệm vụ và bước đi','Quá độ là quá trình lâu dài, có nhiều bước và nhiều hình thức tổ chức kinh tế – xã hội đan xen. Cần phát triển lực lượng sản xuất, xây dựng quan hệ sản xuất phù hợp, tăng cường quản lý và giải quyết các vấn đề văn hóa, xã hội.','Tính lâu dài không phải lý do bỏ qua mục tiêu, mà là căn cứ lựa chọn bước đi có điều kiện thực hiện. Những phương hướng trên trang được diễn giải theo giáo trình 2021; website không tự bổ sung kết luận về văn kiện hay chính sách ban hành sau thời điểm ấy.']
 ],
 '3-4': [
  ['Tám đặc trưng của xã hội hướng tới','Theo nội dung Cương lĩnh được giáo trình dẫn lại, xã hội hướng tới có: dân giàu, nước mạnh, dân chủ, công bằng, văn minh; do nhân dân làm chủ; kinh tế phát triển cao dựa trên lực lượng sản xuất hiện đại và quan hệ sản xuất tiến bộ, phù hợp; văn hóa tiên tiến, đậm đà bản sắc dân tộc.','Bốn đặc trưng tiếp theo là con người có cuộc sống ấm no, tự do, hạnh phúc và điều kiện phát triển toàn diện; các dân tộc bình đẳng, đoàn kết, tôn trọng và giúp nhau phát triển; nhà nước pháp quyền XHCN của nhân dân, do nhân dân, vì nhân dân do Đảng Cộng sản lãnh đạo; quan hệ hữu nghị và hợp tác với các nước.'],
  ['Tám phương hướng xây dựng','Nhóm phương hướng về nền tảng phát triển gồm công nghiệp hóa, hiện đại hóa gắn với kinh tế tri thức và bảo vệ tài nguyên, môi trường; phát triển kinh tế thị trường định hướng XHCN; xây dựng văn hóa, con người, nâng cao đời sống và thực hiện tiến bộ, công bằng xã hội; bảo đảm quốc phòng và an ninh.','Nhóm phương hướng về tổ chức và quan hệ gồm đối ngoại độc lập, tự chủ, hòa bình, hợp tác và hội nhập; xây dựng dân chủ XHCN, đại đoàn kết và mặt trận thống nhất; xây dựng nhà nước pháp quyền XHCN; xây dựng Đảng trong sạch, vững mạnh. Phương hướng là các nhiệm vụ thực hiện, khác với đặc trưng mô tả xã hội hướng tới.'],
  ['Giải quyết các mối quan hệ lớn','Giáo trình nhấn mạnh việc xử lý đồng thời các mối quan hệ như đổi mới – ổn định – phát triển, kinh tế – chính trị, lực lượng sản xuất – quan hệ sản xuất, tăng trưởng – văn hóa – tiến bộ và công bằng xã hội. Các mục tiêu có thể hỗ trợ nhau nhưng cũng đòi hỏi lựa chọn và cân đối trong thực tiễn.','Khi liên hệ, nên chọn một mối quan hệ, giải thích hai phía và chỉ ra điều kiện để phối hợp. Ví dụ giả định về giao thông xanh có thể giúp xem quan hệ giữa phát triển kinh tế, môi trường và cơ hội tiếp cận, nhưng không thể đại diện đầy đủ cho toàn bộ tám phương hướng.']
 ],
 '4-1': [
  ['Ba cách tiếp cận dân chủ','Dân chủ có thể được tiếp cận như một giá trị xã hội về quyền của con người, một hình thức tổ chức quyền lực nhà nước và một nguyên tắc tổ chức, hoạt động. Phân biệt các cách tiếp cận giúp tránh dùng một nghĩa để trả lời mọi câu hỏi.','Với tư cách chế độ chính trị, dân chủ có tính lịch sử và gắn với những điều kiện kinh tế – xã hội cụ thể. Với tư cách giá trị, khát vọng về quyền làm chủ và sự tham gia có ý nghĩa rộng hơn sự tồn tại của một mô hình nhà nước riêng biệt.'],
  ['Bản chất chính trị, kinh tế, tư tưởng – văn hóa','Về chính trị, dân chủ XHCN đặt quyền lực thuộc về nhân dân và được thực hiện dưới sự lãnh đạo của giai cấp công nhân thông qua Đảng Cộng sản. Phân tích bản chất giai cấp cần đi cùng tính nhân dân và tính dân tộc, không tách những mặt ấy thành các thuộc tính độc lập.','Về kinh tế, nền tảng là chế độ sở hữu và tổ chức sản xuất hướng tới lợi ích của nhân dân lao động. Về tư tưởng – văn hóa, dân chủ gắn với hệ giá trị, sự kế thừa văn hóa và các điều kiện nâng cao năng lực tham gia. Quyền được nêu ra cần có điều kiện vật chất và tổ chức để thực hiện.'],
  ['Dân là chủ và dân làm chủ','Dân là chủ nói đến vị trí của nhân dân như chủ thể quyền lực; dân làm chủ nhấn mạnh việc thực hiện quyền ấy trong hoạt động cụ thể. Hai ý liên hệ chặt chẽ: quyền làm chủ cần được hiện thực hóa bằng thông tin, cơ chế tham gia và trách nhiệm của tổ chức thực thi.','Cần xem dân chủ trong cả chính trị, kinh tế và đời sống văn hóa – xã hội. Một cuộc họp có đông người chưa đủ cho thấy người tham gia có thông tin, có tiếng nói và nhận được phản hồi; phải phân tích cả quá trình.']
 ],
 '4-2': [
  ['Sự ra đời và bản chất nhà nước XHCN','Nhà nước XHCN được hình thành từ quá trình cách mạng và việc tổ chức quyền lực của giai cấp công nhân cùng nhân dân lao động. Theo giáo trình, đây là nhà nước kiểu mới, là công cụ tổ chức xây dựng và bảo vệ xã hội mới.','Bản chất được xem xét trên phương diện chính trị, kinh tế và văn hóa – xã hội. Quyền lực không chỉ được mô tả bằng cơ cấu bộ máy mà còn bằng chủ thể quyền lực, cơ sở kinh tế và mục tiêu phục vụ lợi ích của nhân dân lao động.'],
  ['Phân loại chức năng','Theo phạm vi tác động, có chức năng đối nội và đối ngoại; theo lĩnh vực, có các chức năng chính trị, kinh tế, văn hóa và xã hội. Đây là các cách phân loại theo tiêu chí khác nhau, nên một hoạt động có thể được xem xét từ nhiều góc độ.','Theo tính chất quyền lực, giáo trình phân tích chức năng tổ chức xây dựng gắn với bảo vệ chế độ mới. Tổ chức và quản lý kinh tế, phát triển xã hội là nhiệm vụ quan trọng, phức tạp; không nên chỉ nhìn nhà nước qua một loại hoạt động.'],
  ['Từ chức năng đến năng lực thực hiện','Một chức năng chỉ có ý nghĩa thực tế khi có tổ chức, nguồn lực, nhân lực và cơ chế kiểm tra. Ví dụ giả định về cung cấp dịch vụ công cần xem cả việc xác định nhu cầu, phân bổ nguồn lực, thực hiện và đánh giá kết quả.','Phân biệt bản chất, chức năng và hiệu quả hoạt động giúp lập luận rõ ràng. Bản chất trả lời nhà nước gắn với lực lượng và mục tiêu nào; chức năng trả lời làm gì; hiệu quả cần được đánh giá bằng dữ liệu và tiêu chí phù hợp.']
 ],
 '4-3': [
  ['Dân chủ là cơ sở xây dựng nhà nước','Dân chủ tạo điều kiện để nhân dân lựa chọn đại diện, tham gia quản lý và kiểm tra hoạt động của cơ quan thực thi quyền lực. Thông tin, khả năng tham gia và cơ chế phản hồi là những điều kiện giúp ý chí và lợi ích của nhân dân đi vào hoạt động nhà nước.','Nếu các nguyên tắc dân chủ bị vi phạm, quyền lực có thể xa rời mục tiêu phục vụ nhân dân. Vì thế dân chủ không chỉ xuất hiện ở khâu hình thành tổ chức mà còn cần trong quá trình hoạt động và đánh giá trách nhiệm.'],
  ['Nhà nước bảo đảm việc thực hiện dân chủ','Nhà nước thể chế hóa quyền làm chủ, tổ chức các điều kiện thực hiện và bảo vệ những quyền ấy. Quan hệ giữa dân chủ và nhà nước có hai chiều: dân chủ là nền tảng, còn nhà nước là công cụ tổ chức và bảo đảm việc thực hiện.','Cần tránh xem dân chủ như lời tuyên bố, hoặc xem bộ máy có thể tự bảo đảm quyền làm chủ mà không cần cơ chế tham gia và kiểm tra. Việc vận hành phải gắn với trách nhiệm, pháp luật và năng lực thực thi.'],
  ['Dân chủ trực tiếp và dân chủ đại diện','Dân chủ trực tiếp thể hiện khi người dân trực tiếp tham gia quyết định hoặc bày tỏ ý kiến đối với vấn đề chung. Dân chủ đại diện được thực hiện thông qua các chủ thể đại diện do nhân dân lựa chọn; hai hình thức có thể bổ sung nhau.','Trong tình huống giả định về cải tạo khu dân cư, góp ý trực tiếp và chuyển ý kiến qua đại diện là hai kênh tham gia. Để đánh giá, cần hỏi ai được tiếp cận thông tin, ý kiến được xử lý thế nào, có phản hồi hay không và người dân có thể theo dõi việc thực hiện ra sao.']
 ],
 '4-4': [
  ['Những đặc điểm được trình bày trong giáo trình','Nhà nước pháp quyền XHCN Việt Nam là nhà nước của nhân dân, do nhân dân, vì nhân dân; tổ chức và hoạt động trên cơ sở Hiến pháp và pháp luật; quyền lực nhà nước thống nhất, có phân công, phối hợp và kiểm soát giữa các cơ quan thực hiện quyền lập pháp, hành pháp và tư pháp.','Các đặc điểm còn gắn với sự lãnh đạo của Đảng Cộng sản Việt Nam, việc tôn trọng và bảo đảm quyền con người, quyền công dân, cùng trách nhiệm của cơ quan và cán bộ thực thi. Đây là phần diễn giải khái niệm trong giáo trình 2021, không phải hướng dẫn áp dụng một quy định pháp luật hiện hành.'],
  ['Vì sao cần kiểm soát quyền lực?','Phân công nhiệm vụ làm rõ trách nhiệm; phối hợp tránh đứt gãy giữa các khâu; kiểm soát giúp hạn chế lạm quyền và sự tha hóa quyền lực. Ba yêu cầu cần được xem trong mối liên hệ, không thể chỉ nhấn mạnh một phía.','Kiểm soát còn gắn với sự tham gia của nhân dân, giám sát xã hội và trách nhiệm của tổ chức. Khi phân tích một mô hình, cần làm rõ ai có quyền, ai chịu trách nhiệm và bằng cách nào có thể kiểm tra việc thực hiện quyền ấy.'],
  ['Phương hướng xây dựng và hoàn thiện','Các phương hướng bao gồm xây dựng tổ chức tinh gọn, nâng cao chất lượng cán bộ, hoàn thiện cơ chế quản lý, tăng cường kiểm tra và phòng ngừa tham nhũng, thực hiện quyền làm chủ của nhân dân. Năng lực quản trị và phẩm chất của người thực thi phải đi cùng cơ chế trách nhiệm.','Một bài liên hệ nên chọn vấn đề cụ thể như minh bạch thông tin hoặc chất lượng dịch vụ công, nêu tiêu chí đánh giá và dữ kiện cần thu thập. Tránh kết luận hiệu quả từ khẩu hiệu hoặc từ một trải nghiệm cá nhân duy nhất.']
 ],
 '5-1': [
  ['Các loại hình cơ cấu xã hội','Cơ cấu xã hội là hệ thống những cộng đồng người và quan hệ giữa chúng. Có thể nghiên cứu cơ cấu nghề nghiệp, dân số, dân tộc, tôn giáo và cơ cấu xã hội – giai cấp; mỗi cách phân loại làm rõ một phương diện của đời sống xã hội.','Một người có thể đồng thời thuộc nhiều nhóm khác nhau. Do đó không nên dùng thông tin về nghề nghiệp, dân tộc hay độ tuổi để thay cho phân tích vị trí trong các quan hệ kinh tế – xã hội. Các cơ cấu có liên hệ nhưng không đồng nhất.'],
  ['Cơ cấu xã hội – giai cấp và vị trí của nó','Cơ cấu xã hội – giai cấp gồm các giai cấp, tầng lớp và quan hệ giữa họ, gắn với sở hữu tư liệu sản xuất, tổ chức lao động và phân phối. Những quan hệ ấy liên hệ trực tiếp với lợi ích, tổ chức chính trị và hoạt động của nhà nước.','Giáo trình coi cơ cấu xã hội – giai cấp có vị trí quan trọng hàng đầu vì biến đổi của nó ảnh hưởng tới nhiều cơ cấu và lĩnh vực khác. Điều này không có nghĩa mọi hiện tượng chỉ có một nguyên nhân giai cấp; cần tôn trọng tính đa dạng của các quan hệ xã hội.'],
  ['Cách đọc một biến đổi cơ cấu','Khi một địa phương chuyển từ nông nghiệp sang công nghiệp và dịch vụ, không chỉ tỷ trọng nghề nghiệp thay đổi. Cần xem quyền sử dụng nguồn lực, thu nhập, điều kiện sống, tổ chức cộng đồng và quan hệ lợi ích của các nhóm bị tác động.','Số lượng của một nhóm là dữ kiện cần thiết nhưng chưa đủ. Phân tích cơ cấu phải trả lời nhóm ấy ở vị trí nào, quan hệ với nhóm khác ra sao và những cơ chế nào định hình cơ hội phát triển của họ.']
 ],
 '5-2': [
  ['Xu hướng biến đổi trong thời kỳ quá độ','Biến đổi cơ cấu xã hội – giai cấp gắn với chuyển đổi cơ cấu kinh tế, hình thức sở hữu và phân công lao động. Công nghiệp hóa, đô thị hóa và phát triển dịch vụ tạo ra sự dịch chuyển giữa các nhóm, đồng thời làm thay đổi chất lượng và cơ cấu nội bộ của từng nhóm.','Quá trình này có thể xuất hiện phân hóa, những lợi ích khác nhau và sự đa dạng của tầng lớp xã hội. Cần phân tích cả sự khác biệt lẫn xu hướng liên kết, không chỉ nhấn mạnh một phía.'],
  ['Tính tất yếu về chính trị và kinh tế của liên minh','Về chính trị, liên minh giữa giai cấp công nhân với nông dân và các tầng lớp lao động tạo cơ sở xã hội cho việc thực hiện các nhiệm vụ cách mạng và xây dựng xã hội mới. Sức mạnh của một lực lượng không tách khỏi quan hệ với những lực lượng có lợi ích gắn bó.','Về kinh tế, công nghiệp, nông nghiệp và hoạt động khoa học – công nghệ phụ thuộc và bổ sung cho nhau. Sự kết hợp nguồn lực, kỹ thuật, thị trường và lợi ích là điều kiện để phát triển sản xuất; liên minh phải có nội dung hợp tác thực chất.'],
  ['Cơ sở lợi ích và những yêu cầu đặt ra','Liên minh dựa trên việc giải quyết hài hòa lợi ích, không có nghĩa mọi nhóm có nhu cầu hoàn toàn giống nhau. Khác biệt về nguồn lực, vị trí và điều kiện sống cần được nhận diện để xây dựng cơ chế hợp tác và chia sẻ phù hợp.','Nếu chỉ huy động đóng góp mà không quan tâm lợi ích và cơ hội của từng nhóm, hợp tác khó bền vững. Phân tích một liên kết cần xem mỗi bên đóng góp gì, được hưởng gì và có khả năng tham gia vào quyết định chung ra sao.']
 ],
 '5-3': [
  ['Những lực lượng trong cơ cấu xã hội Việt Nam','Giáo trình phân tích giai cấp công nhân, nông dân, đội ngũ trí thức, doanh nhân và các tầng lớp xã hội trong thời kỳ quá độ. Mỗi lực lượng có vị trí và vai trò riêng; cơ cấu nội bộ cũng biến đổi cùng sự phát triển kinh tế và phân công lao động.','Công nhân gắn với công nghiệp; nông dân là chủ thể quan trọng của nông nghiệp và nông thôn; trí thức gắn với lao động sáng tạo và phát triển tri thức. Liên minh công nhân – nông dân – trí thức là nền tảng quan trọng, đồng thời phải đặt trong khối đại đoàn kết toàn dân.'],
  ['Nội dung kinh tế của liên minh','Nội dung kinh tế là sự kết hợp lợi ích và nguồn lực để phát triển sản xuất, nâng cao đời sống và xây dựng cơ sở vật chất. Công nghiệp cung cấp công cụ và chế biến; nông nghiệp cung cấp nguyên liệu; tri thức và công nghệ hỗ trợ chất lượng, năng suất và tổ chức.','Trong chuỗi nông sản giả định, cần xem cả giá mua, chi phí, rủi ro và quyền tham gia của từng bên. Chuỗi sản xuất là ví dụ về nội dung kinh tế; nó không tự thể hiện đầy đủ bản chất chính trị và văn hóa – xã hội của liên minh.'],
  ['Nội dung chính trị và văn hóa – xã hội','Về chính trị, liên minh tạo nền tảng xã hội cho việc thực hiện quyền làm chủ, bảo vệ và xây dựng chế độ trong sự lãnh đạo của Đảng. Sự gắn bó cần được củng cố thông qua tổ chức, đồng thuận và việc giải quyết những vấn đề lợi ích.','Về văn hóa – xã hội, liên minh gắn với nâng cao trình độ, chăm lo đời sống, phát triển giáo dục, y tế và văn hóa, thực hiện tiến bộ và công bằng. Ba nội dung có quan hệ hữu cơ: thiếu điều kiện sống và cơ hội phát triển thì hợp tác kinh tế và đồng thuận khó bền vững.']
 ],
 '5-4': [
  ['Gắn chuyển đổi cơ cấu với phát triển bền vững','Đẩy mạnh công nghiệp hóa, hiện đại hóa và chuyển đổi cơ cấu kinh tế cần đi cùng nâng cao chất lượng các giai cấp, tầng lớp. Không chỉ tạo thêm việc làm, mà còn cần cải thiện năng lực, điều kiện lao động và khả năng thích ứng của người lao động.','Tăng trưởng phải gắn với phát triển văn hóa, tiến bộ, công bằng xã hội và bảo vệ môi trường. Khi một nhóm chịu chi phí chuyển đổi lớn hơn nhóm khác, cần nhận diện và phân tích cơ chế hỗ trợ thay vì coi thay đổi cơ cấu tự nó giải quyết mọi vấn đề.'],
  ['Chính sách xã hội và giải quyết lợi ích','Giáo trình nhấn mạnh hệ thống chính sách liên quan tới việc làm, thu nhập, giáo dục, đời sống và cơ hội phát triển của các giai cấp, tầng lớp. Mục tiêu là tạo điều kiện để các nhóm phát huy vai trò và tham gia vào quá trình phát triển.','Giải quyết lợi ích phải chú ý cả điểm chung và khác biệt; tạo đồng thuận không đồng nghĩa phủ nhận các mâu thuẫn thực tế. Cần có thông tin, đối thoại và cơ chế để những vấn đề của từng nhóm được nhận diện và xử lý.'],
  ['Tổ chức liên kết và trách nhiệm của người học','Nâng cao hiệu quả hoạt động của các tổ chức chính trị – xã hội và cơ chế hợp tác giúp liên minh có hình thức thực hiện cụ thể. Quan hệ giữa công nghiệp, nông nghiệp và khoa học cần thể hiện bằng hoạt động liên kết, đào tạo và chia sẻ lợi ích.','Sinh viên có thể liên hệ qua việc hiểu vai trò các lực lượng, tôn trọng lao động và vận dụng kiến thức chuyên môn vào những nhu cầu xã hội. Một dự án tình nguyện hoặc hỗ trợ kỹ thuật cần xác định nhu cầu thực tế, người hưởng lợi và cách đánh giá, thay vì chỉ đếm hoạt động.']
 ],
 '6-1': [
  ['Phân biệt quốc gia – dân tộc và tộc người','Theo nghĩa rộng, dân tộc chỉ cộng đồng quốc gia có lãnh thổ ổn định, đời sống kinh tế chung, ngôn ngữ, những đặc điểm văn hóa và sự quản lý của nhà nước. Theo nghĩa hẹp, dân tộc chỉ tộc người với ngôn ngữ, văn hóa và ý thức tự giác tộc người.','Một quốc gia có thể gồm nhiều tộc người. Cách dùng từ cần được xác định ngay từ đầu: nói về chủ quyền quốc gia khác với nói về quan hệ giữa các tộc người trong cùng một quốc gia, dù hai vấn đề có liên hệ.'],
  ['Hai xu hướng khách quan','Xu hướng thứ nhất là những cộng đồng dân tộc muốn tách ra để xác lập sự độc lập, tự chủ; xu hướng thứ hai là các dân tộc có nhu cầu liên hiệp, xích lại gần nhau do sự phát triển của sản xuất và giao lưu. Hai xu hướng diễn ra trong những bối cảnh cụ thể và có thể cùng tồn tại.','Cần phân tích nhu cầu tự chủ trong quan hệ với nhu cầu hợp tác, không xem chúng nhất thiết loại trừ nhau. Mỗi trường hợp phải xét lịch sử, lợi ích, điều kiện phát triển và quan hệ giữa các lực lượng có liên quan.'],
  ['Ba nội dung của cương lĩnh dân tộc','Các dân tộc hoàn toàn bình đẳng; các dân tộc được quyền tự quyết; liên hiệp công nhân tất cả các dân tộc là ba nội dung được giáo trình trình bày. Bình đẳng bao gồm quyền và điều kiện phát triển, chống đặc quyền và áp bức dân tộc.','Quyền tự quyết được phân tích trong hoàn cảnh lịch sử và tương quan lợi ích cụ thể, không đồng nhất với mọi yêu sách tách biệt. Liên hiệp công nhân nhấn mạnh cơ sở đoàn kết giữa người lao động thuộc các dân tộc, tạo sự gắn bó giữa giải quyết vấn đề dân tộc và vấn đề giai cấp.']
 ],
 '6-2': [
  ['Đặc điểm quan hệ dân tộc ở Việt Nam','Giáo trình nêu sự chênh lệch về quy mô dân số, cư trú xen kẽ, khác nhau về trình độ phát triển và nét văn hóa của các tộc người. Các dân tộc có truyền thống đoàn kết và gắn bó trong quá trình dựng nước, giữ nước, tạo nên sự thống nhất trong đa dạng.','Những đặc điểm này đòi hỏi cách tiếp cận phù hợp từng vùng và cộng đồng. Không nên đồng nhất một tộc người với một địa bàn, hoặc dùng bản sắc để suy đoán năng lực và hành vi của một cá nhân.'],
  ['Quan điểm về bình đẳng, đoàn kết và phát triển','Bình đẳng không chỉ là không phân biệt về danh nghĩa, mà còn gắn với điều kiện để các cộng đồng tham gia và phát triển. Đoàn kết đi cùng tôn trọng bản sắc, giúp đỡ lẫn nhau và xử lý những nguyên nhân làm phát sinh chênh lệch.','Chính sách dân tộc theo giáo trình có tính toàn diện, bao gồm kinh tế, chính trị, văn hóa, xã hội và an ninh – quốc phòng. Phát triển kinh tế – xã hội tạo cơ sở vật chất cho bình đẳng và đoàn kết, trong khi văn hóa và sự tham gia củng cố tính bền vững của phát triển.'],
  ['Cách liên hệ có căn cứ','Một ví dụ giả định về học tập ở vùng khó khăn cần xem điều kiện đi lại, ngôn ngữ, hạ tầng, nguồn lực giáo dục và nhu cầu của người học. Biện pháp giống nhau cho mọi nơi chưa chắc tạo cơ hội bình đẳng nếu điều kiện xuất phát khác nhau.','Nên phân biệt nhu cầu của cộng đồng, tiếng nói của cá nhân và thông tin thực tế. Những đặc điểm và phương hướng trên trang được trình bày theo giáo trình 2021; không dùng số liệu cũ như số liệu hiện tại.']
 ],
 '6-3': [
  ['Tôn giáo, tín ngưỡng và mê tín dị đoan','Tôn giáo là hình thái ý thức xã hội với niềm tin, hệ thống quan niệm, nghi lễ và tổ chức nhất định. Tín ngưỡng là niềm tin và sự ngưỡng vọng vào những lực lượng thiêng; hai khái niệm có giao thoa nhưng không hoàn toàn đồng nhất.','Không nên quy mọi hoạt động tín ngưỡng, tôn giáo thành mê tín dị đoan. Phân tích cần dựa vào bản chất hoạt động và tác động thực tế, đồng thời phân biệt niềm tin của cá nhân với cách một tổ chức hoặc cá nhân sử dụng niềm tin ấy.'],
  ['Nguồn gốc và tính chất','Giáo trình phân tích các nguồn gốc tự nhiên – kinh tế – xã hội, nhận thức và tâm lý của tôn giáo. Giới hạn của nhận thức, sự bất lực trước những điều kiện sống và các nhu cầu tinh thần là những yếu tố cần xem xét trong quan hệ với nhau.','Tôn giáo có tính lịch sử, tính quần chúng và trong những điều kiện nhất định có tính chính trị. Mỗi tính chất cần được giải thích theo bối cảnh, tránh gán cùng một động cơ cho mọi người có niềm tin hoặc mọi sinh hoạt tôn giáo.'],
  ['Các nguyên tắc giải quyết vấn đề tôn giáo','Tôn trọng, bảo đảm tự do tín ngưỡng và không tín ngưỡng; khắc phục ảnh hưởng tiêu cực gắn với cải tạo xã hội cũ và xây dựng xã hội mới; phân biệt mặt chính trị và mặt tư tưởng; vận dụng quan điểm lịch sử – cụ thể là các nguyên tắc trong giáo trình.','Tôn trọng niềm tin đi cùng đoàn kết giữa người có và không có tôn giáo. Khi vận dụng trong nhóm học tập, cần trao đổi nhu cầu cụ thể, bảo đảm cơ hội tham gia và tránh định kiến; ví dụ nhỏ này không thay thế toàn bộ nội dung quản lý hay chính sách tôn giáo.']
 ],
 '6-4': [
  ['Sự đan xen của dân tộc và tôn giáo','Bản sắc tộc người, sinh hoạt tôn giáo và tín ngưỡng truyền thống có thể đan xen trong một cộng đồng. Tuy nhiên, một tộc người không nhất thiết chỉ có một tôn giáo, và những người cùng tôn giáo có thể thuộc nhiều tộc người khác nhau.','Quan hệ dân tộc – tôn giáo vì thế cần được xem xét theo địa bàn, lịch sử và sinh hoạt thực tế. Đồng nhất hai khái niệm dễ dẫn tới cách giải thích giản đơn và bỏ qua sự đa dạng nội bộ.'],
  ['Những yêu cầu trong giải quyết quan hệ','Giáo trình nhấn mạnh giữ vững sự đoàn kết, bảo đảm quyền bình đẳng, tôn trọng tự do tín ngưỡng và giải quyết nhu cầu chính đáng trong quan hệ với lợi ích chung. Phát triển kinh tế, văn hóa và đời sống xã hội là cơ sở để củng cố sự gắn bó.','Cần phân biệt hoạt động tín ngưỡng bình thường với việc lợi dụng vấn đề dân tộc hoặc tôn giáo để gây chia rẽ. Không đánh đồng hành vi của một người hay nhóm nhỏ với bản chất của cả một cộng đồng.'],
  ['Thực hành phân tích và tránh định kiến','Khi có khác biệt về lịch sinh hoạt, trang phục hoặc nghi lễ, nên bắt đầu bằng câu hỏi về nhu cầu và điều kiện tham gia. Thỏa thuận dựa trên thông tin cụ thể giúp giữ sự tôn trọng và cơ hội bình đẳng.','Một lập luận tốt cần chỉ ra dữ kiện nào thuộc bản sắc, dữ kiện nào thuộc lợi ích và đâu là suy đoán. Các nhận định về chính sách trên website nằm trong phạm vi giáo trình; không phải kết luận pháp lý cho một trường hợp cụ thể.']
 ],
 '7-1': [
  ['Gia đình và các quan hệ tạo thành','Gia đình là một cộng đồng xã hội đặc biệt, hình thành và duy trì chủ yếu trên cơ sở quan hệ hôn nhân, huyết thống và nuôi dưỡng, gắn với quyền và nghĩa vụ giữa các thành viên. Quan hệ gia đình không chỉ là sống chung mà còn có sự chăm sóc và trách nhiệm.','Phân biệt các cơ sở quan hệ giúp hiểu sự đa dạng của gia đình và vai trò của nuôi dưỡng. Khi phân tích cần xem các thành viên thực hiện trách nhiệm và hỗ trợ nhau như thế nào, không chỉ dựa vào số người hoặc hình thức cư trú.'],
  ['Vị trí: tế bào xã hội, tổ ấm, cầu nối','Gia đình là tế bào của xã hội vì gắn với tái sản xuất con người và các hoạt động cơ bản của đời sống. Gia đình cũng là môi trường đáp ứng nhu cầu tình cảm, chăm sóc, tạo sự an toàn và giúp mỗi người hình thành nhân cách.','Gia đình là cầu nối giữa cá nhân và xã hội: mỗi người tiếp nhận giá trị, chuẩn mực và điều kiện sống thông qua gia đình, đồng thời chịu tác động của nhà trường, kinh tế và cộng đồng. Vì vậy gia đình và xã hội có quan hệ hai chiều.'],
  ['Các chức năng cơ bản','Tái sản xuất con người; nuôi dưỡng và giáo dục; kinh tế và tổ chức tiêu dùng; thỏa mãn nhu cầu tâm sinh lý, duy trì tình cảm là các chức năng cơ bản được giáo trình phân tích. Các chức năng liên hệ chặt chẽ và chịu tác động của điều kiện kinh tế – xã hội.','Công việc chăm sóc, dạy con và tổ chức đời sống có giá trị ngay cả khi không tạo thu nhập trực tiếp. Một phân tích về gia đình cần nhìn cả lao động có trả công và lao động chăm sóc, thay vì chỉ so sánh tiền lương của các thành viên.']
 ],
 '7-2': [
  ['Cơ sở kinh tế – xã hội','Sự phát triển của lực lượng sản xuất và những biến đổi của quan hệ sở hữu tạo điều kiện cải thiện đời sống, mở rộng cơ hội lao động và giảm các quan hệ phụ thuộc. Đây là nền tảng vật chất quan trọng để xây dựng quan hệ gia đình tiến bộ.','Điều kiện kinh tế không chỉ là mức thu nhập: nhà ở, thời gian lao động, khả năng tiếp cận dịch vụ và hỗ trợ chăm sóc cũng ảnh hưởng tới đời sống gia đình. Quan hệ bình đẳng khó bền vững nếu một thành viên thiếu cơ hội học tập và tham gia xã hội.'],
  ['Cơ sở chính trị – xã hội','Giáo trình gắn xây dựng gia đình với nhà nước, các thiết chế và hệ thống chính sách nhằm bảo vệ quyền, lợi ích của thành viên, đặc biệt việc khắc phục bất bình đẳng đối với phụ nữ. Các điều kiện tổ chức giúp quyền và trách nhiệm có cơ sở thực hiện.','Đây là phân tích vai trò của thể chế trong giáo trình, không phải tư vấn thủ tục pháp lý. Khi nghiên cứu một vấn đề gia đình cần phân biệt quy định, điều kiện thực thi và trải nghiệm của người có liên quan.'],
  ['Cơ sở văn hóa và sự kết hợp các điều kiện','Giáo dục, trình độ dân trí, giá trị tôn trọng và bình đẳng giúp hình thành cách ứng xử tiến bộ trong gia đình. Những điều kiện vật chất thuận lợi chưa tự tạo ra quan hệ tốt nếu còn quan niệm áp đặt hoặc thiếu năng lực giải quyết mâu thuẫn.','Kinh tế, chính trị – xã hội và văn hóa cần phát triển đồng bộ, cùng với chế độ hôn nhân tiến bộ. Chỉ vận động thay đổi thái độ mà bỏ qua gánh nặng thời gian, thu nhập và chăm sóc thì khó tạo ra thay đổi bền vững.']
 ],
 '7-3': [
  ['Hôn nhân tự nguyện và trách nhiệm','Hôn nhân tiến bộ dựa trên tình yêu và sự tự nguyện của những người kết hôn. Tự nguyện loại trừ sự cưỡng ép, đồng thời đòi hỏi tôn trọng quyết định, nhân phẩm và sự phát triển của nhau trong đời sống chung.','Tự do lựa chọn không đồng nghĩa bỏ qua trách nhiệm với gia đình và các thành viên phụ thuộc. Cần phân tích quyền cùng với nghĩa vụ, điều kiện thực hiện và những hậu quả xã hội của quyết định.'],
  ['Một vợ một chồng và bình đẳng vợ chồng','Giáo trình trình bày hôn nhân một vợ một chồng và sự bình đẳng giữa vợ, chồng như những nội dung của hôn nhân tiến bộ. Bình đẳng thể hiện trong quyền quyết định, trách nhiệm, cơ hội phát triển và cách tôn trọng lợi ích của nhau.','Phân chia công việc không nhất thiết mọi người làm số việc giống nhau, mà cần phù hợp thời gian, năng lực, nhu cầu và sự thỏa thuận. Không mặc định việc chăm sóc thuộc về một giới hoặc thu nhập cao hơn tạo quyền quyết định lớn hơn.'],
  ['Sự bảo đảm xã hội và bài tập vận dụng','Hôn nhân được bảo đảm về mặt pháp lý thể hiện trách nhiệm của xã hội trong bảo vệ quan hệ và quyền của các thành viên. Nội dung trên trang là lý luận theo giáo trình 2021, không cung cấp kết luận về điều kiện hay thủ tục pháp luật hiện hành.','Trong tình huống chia sẻ việc nhà, hãy lập danh sách công việc có và không có thu nhập, xác định thời gian, cơ hội bị ảnh hưởng rồi đề xuất cách phân chia. Lập luận cần giải thích vì sao giải pháp tăng cơ hội và giảm bất bình đẳng, thay vì chỉ nêu một lời kêu gọi chung.']
 ],
 '7-4': [
  ['Biến đổi quy mô và các chức năng','Công nghiệp hóa, đô thị hóa và thay đổi điều kiện sống tác động tới quy mô, hình thức cư trú và quan hệ giữa các thế hệ. Xu hướng gia đình nhỏ hơn tạo thêm tính độc lập nhưng cũng đặt ra nhu cầu mới về chăm sóc và hỗ trợ.','Các chức năng kinh tế, giáo dục và chăm sóc ngày càng có sự chia sẻ với các thiết chế xã hội. Gia đình vẫn giữ vai trò quan trọng, nhưng cách thực hiện thay đổi khi dịch vụ, công việc và cơ hội học tập phát triển.'],
  ['Biến đổi quan hệ và những vấn đề đặt ra','Quan hệ vợ chồng và giữa cha mẹ, con cái chịu tác động của thay đổi nghề nghiệp, thu nhập, giáo dục và giá trị sống. Sự dân chủ, bình đẳng có cơ hội được mở rộng; đồng thời có thể xuất hiện căng thẳng về thời gian, khoảng cách thế hệ và trách nhiệm chăm sóc.','Không nên chỉ đánh giá biến đổi như suy giảm hoặc tiến bộ hoàn toàn. Cần xác định điều gì được cải thiện, nhóm nào chịu gánh nặng và các điều kiện hỗ trợ còn thiếu. Nhận xét về gia đình phải dựa trên dữ liệu và không quy lỗi cho một giới hay một thế hệ.'],
  ['Bốn phương hướng xây dựng gia đình','Giáo trình nêu tăng cường nhận thức và trách nhiệm của hệ thống tổ chức; phát triển kinh tế – xã hội và nâng cao đời sống; kế thừa giá trị tốt đẹp của gia đình truyền thống đồng thời tiếp thu tiến bộ; nâng cao chất lượng phong trào xây dựng gia đình văn hóa.','Vận dụng cần kết nối tình cảm, trách nhiệm và bình đẳng với điều kiện vật chất, giáo dục và hỗ trợ xã hội. Gia đình tốt đẹp không chỉ được mô tả bằng hình ảnh hòa thuận, mà còn bằng sự an toàn, cơ hội phát triển và sự tôn trọng giữa các thành viên.']
 ]
};
for (const chapter of chapters) {
 chapter.minutes = [65,65,75,70,65,75,65][chapter.id-1];
 for (const lesson of chapter.lessons) {
  lesson.sections = content[lesson.id].map(([title,...paragraphs])=>({title,paragraphs,pages:lesson.pages}));
  lesson.review = `Hãy giải thích bằng lời của bạn: ${lesson.sections[1].title.toLowerCase()}. Chỉ ra một ý liên hệ với mục khác trong chương và nêu căn cứ từ giáo trình.`;
 }
}
fs.writeFileSync(file,JSON.stringify(chapters,null,2)+'\n');
console.log('Expanded all 28 lessons with 84 detailed sections and 28 review prompts.');
